Url-encode colons in names of raw proxy assets
sonatype/nexus-public pull request #75
Opened 2020-07-21 19:31 UTC by episource

Without encoding colons, resolving of upstream urls using [URI#resolve](https://docs.oracle.com/javase/8/docs/api/java/net/URI.html#resolve-java.net.URI-) (via ProxyFacetSupport#fetch) fails for components with names including colons: This is due to URI#resolve returning the given uri unchanged/unresolved if it is opaque or absolute. See [URI class reference](https://docs.oracle.com/javase/8/docs/api/java/net/URI.html) for details.

Unpatched nexus fails to resolve the upstream url of affected assets, leading to an error message like
```
nexus3_1  | 2020-07-19 21:56:57,573+0000 WARN  [qtp1665000230-434] *UNKNOWN org.sonatype.nexus.orient.raw.internal.RawProxyFacet - Exception org.apache.http.client.ClientProtocolException: URI does not specify a valid host name: ethtool-1:5.7-1-x86_64.pkg.tar.zst checking remote for update, proxy repo archlinux_x64-extra-proxy failed to fetch ethtool-1:5.7-1-x86_64.pkg.tar.zst, content not in cache.
``` 

I stumbled upon this issue when setting up a raw proxy repository for an upstream archlinux repository. Archlinux package file names commonly contain colons.

2020-08-20 21:40 UTC, dawidsawa requested changes
@episource Thank you for the pull request. In the current form we cannot merge it, because it doesn't include any tests to protect us from future regressions. We also believe the issue might be a bit broader and we would need that other special characters are handled properly.

2023-12-30 21:21 UTC, episource commented
Looks like this will be finally [fixed within the upcoming release](https://github.com/sonatype/nexus-public/commit/89ab162d2d6f066e17205788c80acea774c0659d#diff-6cc56b98d9d34deb295f50cc8885f3d9fad97edbbdce79a43b0b7c546f4fbe83)!

2024-01-23 21:03 UTC, episource commented
This was finally [addressed by Nexus 3.64.0](https://github.com/sonatype/nexus-public/commit/7d842d55e686054f443d753faad9d72c347f3870).

2024-01-23 21:03 UTC, closed without merging

2024-01-23 21:20 UTC, nblair commented
Thanks @episource  for catching that and updating here!